name: Project Deployment
on: [push,workflow_dispatch]
jobs:
  dependency-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Code
        uses: actions/checkout@v3

      - name: Install-NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install-Dependency-Manager
        uses: pnpm/action-setup@v3
        with:
          version: 7.25.0

      - name: Install-Dependencies
        run: pnpm install --frozen-lockfile

  deploy:
    needs: dependency-installation
    runs-on: ubuntu-latest
    steps:
      - name: Get-Code
        uses: actions/checkout@v3

      - name: Install-NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install-Dependency-Manager
        uses: pnpm/action-setup@v3
        with:
          version: 7.25.0

      - name: Install-Dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy
        run: echo "Deploying..."
